version: '3.8'

services:
  ml-notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
      - ./sml.py:/workspace/sml.py
    environment:
      - JUPYTER_ENABLE_LAB=yes
    container_name: ml-backpropagation
    restart: unless-stopped